package ninja.cooperstuff.pokemon.init;

import ninja.cooperstuff.debug.Debug;
import ninja.cooperstuff.pokemon.move.*;

import static ninja.cooperstuff.pokemon.init.Types.*;
import static ninja.cooperstuff.pokemon.move.Move.AttackType.*;

public class Moves implements Init.Initializer {
	public static final Move absorb = new DefaultMove("Absorb", GRASS, SPECIAL, 20, 100, 25);
	public static final Move acid = new DefaultMove("Acid", POISON, SPECIAL, 40, 100, 30);
	public static final Move acidArmor = new DefaultMove("Acid Armor", POISON, STATUS, 0, 0, 20);
	public static final Move agility = new DefaultMove("Agility", PSYCHIC, STATUS, 0, 0, 30);
	public static final Move amnesia = new DefaultMove("Amnesia", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move auroraBeam = new DefaultMove("Aurora Beam", ICE, SPECIAL, 65, 100, 20);
	public static final Move barrage = new DefaultMove("Barrage", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move barrier = new DefaultMove("Barrier", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move bide = new DefaultMove("Bide", NORMAL, PHYSICAL, 0, 0, 10);
	public static final Move bind = new DefaultMove("Bind", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move bite = new DefaultMove("Bite", DARK, PHYSICAL, 60, 100, 25);
	public static final Move blizzard = new DefaultMove("Blizzard", ICE, SPECIAL, 110, 70, 5);
	public static final Move bodySlam = new DefaultMove("Body Slam", NORMAL, PHYSICAL, 85, 100, 15);
	public static final Move boneClub = new DefaultMove("Bone Club", GROUND, PHYSICAL, 65, 85, 20);
	public static final Move bonemerang = new DefaultMove("Bonemerang", GROUND, PHYSICAL, 50, 90, 10);
	public static final Move bubble = new DefaultMove("Bubble", WATER, SPECIAL, 40, 100, 30);
	public static final Move bubbleBeam = new DefaultMove("Bubble Beam", WATER, SPECIAL, 65, 100, 20);
	public static final Move clamp = new DefaultMove("Clamp", WATER, PHYSICAL, 35, 85, 10);
	public static final Move cometPunch = new DefaultMove("Comet Punch", NORMAL, PHYSICAL, 18, 85, 15);
	public static final Move confuseRay = new DefaultMove("Confuse Ray", GHOST, STATUS, 0, 100, 10);
	public static final Move confusion = new DefaultMove("Confusion", PSYCHIC, SPECIAL, 50, 100, 25);
	public static final Move constrict = new DefaultMove("Constrict", NORMAL, PHYSICAL, 10, 100, 35);
	public static final Move conversion = new DefaultMove("Conversion", NORMAL, STATUS, 0, 0, 30);
	public static final Move counter = new DefaultMove("Counter", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move crabhammer = new DefaultMove("Crabhammer", WATER, PHYSICAL, 100, 90, 10);
	public static final Move cut = new DefaultMove("Cut", NORMAL, PHYSICAL, 50, 95, 30);
	public static final Move defenceCurl = new DefaultMove("Defence Curl", NORMAL, STATUS, 0, 0, 40);
	public static final Move dig = new DefaultMove("Dig", GROUND, PHYSICAL, 80, 100, 10);
	public static final Move disable = new DefaultMove("Disable", NORMAL, STATUS, 0, 100, 20);
	public static final Move dizzyPunch = new DefaultMove("Dizzy Punch", NORMAL, PHYSICAL, 70, 100, 10);
	public static final Move doubleKick = new DefaultMove("Double Kick", FIGHTING, PHYSICAL, 30, 100, 30);
	public static final Move doubleSlap = new DefaultMove("Double Slap", NORMAL, PHYSICAL, 15, 85, 10);
	public static final Move doubleTeam = new DefaultMove("Double Team", NORMAL, STATUS, 0, 0, 15);
	public static final Move doubleEdge = new DefaultMove("Double Edge", NORMAL, PHYSICAL, 120, 100, 15);
	public static final Move dragonRage = new DefaultMove("Dragon Rage", DRAGON, SPECIAL, 0, 100, 10);
	public static final Move dreamEater = new DefaultMove("Dream Eater", PSYCHIC, SPECIAL, 100, 100, 15);
	public static final Move drillPeck = new DefaultMove("Drill Peck", FLYING, PHYSICAL, 80, 100, 20);
	public static final Move earthquake = new DefaultMove("Earthquake", GROUND, PHYSICAL, 100, 100, 10);
	public static final Move eggBomb = new DefaultMove("Egg Bomb", NORMAL, PHYSICAL, 100, 75, 10);
	public static final Move ember = new Ember("Ember", FIRE, SPECIAL, 40, 100, 25);
	public static final Move explosion = new DefaultMove("Explosion", NORMAL, PHYSICAL, 250, 100, 5);
	public static final Move fireBlast = new DefaultMove("Fire Blast", FIRE, SPECIAL, 110, 85, 5);
	public static final Move firePunch = new DefaultMove("Fire Punch", FIRE, PHYSICAL, 75, 100, 15);
	public static final Move fireSpin = new DefaultMove("Fire Spin", FIRE, SPECIAL, 35, 85, 15);
	public static final Move fissure = new DefaultMove("Fissure", GROUND, PHYSICAL, 0, 0, 5);
	public static final Move flamethrower = new DefaultMove("Flamethrower", FIRE, SPECIAL, 90, 100, 15);
	public static final Move flash = new DefaultMove("Flash", NORMAL, STATUS, 0, 100, 20);
	public static final Move fly = new DefaultMove("Fly", FLYING, PHYSICAL, 90, 95, 15);
	public static final Move focusEnergy = new DefaultMove("Focus Energy", NORMAL, STATUS, 0, 0, 30);
	public static final Move furyAttack = new DefaultMove("Fury Attack", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move furySwipes = new DefaultMove("Fury Swipes", NORMAL, PHYSICAL, 18, 80, 15);
	public static final Move glare = new DefaultMove("Glare", NORMAL, STATUS, 0, 100, 30);
	public static final Move growl = new DefaultMove("Growl", NORMAL, STATUS, 0, 100, 40);
	public static final Move growth = new DefaultMove("Growth", NORMAL, STATUS, 0, 0, 40);
	public static final Move guillotine = new DefaultMove("Guillotine", NORMAL, PHYSICAL, 0, 0, 5);
	public static final Move gust = new DefaultMove("Gust", FLYING, SPECIAL, 40, 100, 35);
	public static final Move harden = new DefaultMove("Harden", NORMAL, STATUS, 0, 0, 30);
	public static final Move haze = new DefaultMove("Haze", ICE, STATUS, 0, 0, 30);
	public static final Move headbutt = new DefaultMove("Headbutt", NORMAL, PHYSICAL, 70, 100, 15);
	public static final Move highJumpKick = new DefaultMove("High Jump Kick", FIGHTING, PHYSICAL, 130, 90, 10);
	public static final Move hornAttack = new DefaultMove("Horn Attack", NORMAL, PHYSICAL, 65, 100, 25);
	public static final Move hornDrill = new DefaultMove("Horn Drill", NORMAL, PHYSICAL, 0, 0, 5);
	public static final Move hydroPump = new DefaultMove("Hydro Pump", WATER, SPECIAL, 110, 80, 5);
	public static final Move hyperBeam = new DefaultMove("Hyper Beam", NORMAL, SPECIAL, 150, 90, 5);
	public static final Move hyperFang = new DefaultMove("Hyper Fang", NORMAL, PHYSICAL, 80, 90, 15);
	public static final Move hypnosis = new DefaultMove("Hypnosis", PSYCHIC, STATUS, 0, 60, 20);
	public static final Move iceBeam = new DefaultMove("Ice Beam", ICE, SPECIAL, 90, 100, 10);
	public static final Move icePunch = new DefaultMove("Ice Punch", ICE, PHYSICAL, 75, 100, 15);
	public static final Move jumpKick = new DefaultMove("Jump Kick", FIGHTING, PHYSICAL, 100, 95, 10);
	public static final Move karateChop = new DefaultMove("Karate Chop", FIGHTING, PHYSICAL, 50, 100, 25);
	public static final Move kinesis = new DefaultMove("Kinesis", PSYCHIC, STATUS, 0, 80, 15);
	public static final Move leechLife = new DefaultMove("Leech Life", BUG, PHYSICAL, 80, 100, 10);
	public static final Move leechSeed = new DefaultMove("Leech Seed", GRASS, STATUS, 0, 90, 10);
	public static final Move leer = new DefaultMove("Leer", NORMAL, STATUS, 0, 100, 30);
	public static final Move lick = new DefaultMove("Lick", GHOST, PHYSICAL, 30, 100, 30);
	public static final Move lightScreen = new DefaultMove("Light Screen", PSYCHIC, STATUS, 0, 0, 30);
	public static final Move lovelyKiss = new DefaultMove("Lovely Kiss", NORMAL, STATUS, 0, 75, 10);
	public static final Move lowKick = new DefaultMove("Low Kick", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move meditate = new DefaultMove("Meditate", PSYCHIC, STATUS, 0, 0, 40);
	public static final Move megaDrain = new DefaultMove("Mega Drain", GRASS, SPECIAL, 40, 100, 15);
	public static final Move megaKick = new DefaultMove("Mega Kick", NORMAL, PHYSICAL, 120, 75, 5);
	public static final Move megaPunch = new DefaultMove("Mega Punch", NORMAL, PHYSICAL, 80, 85, 20);
	public static final Move metronome = new DefaultMove("Metronome", NORMAL, STATUS, 0, 0, 10);
	public static final Move mimic = new DefaultMove("Mimic", NORMAL, STATUS, 0, 0, 10);
	public static final Move minimize = new DefaultMove("Minimize", NORMAL, STATUS, 0, 0, 10);
	public static final Move mirrorMove = new DefaultMove("Mirror Move", FLYING, STATUS, 0, 0, 20);
	public static final Move mist = new DefaultMove("Mist", ICE, STATUS, 0, 0, 30);
	public static final Move nightShade = new DefaultMove("Night Shade", GHOST, SPECIAL, 0, 100, 15);
	public static final Move payDay = new DefaultMove("Pay Day", NORMAL, PHYSICAL, 40, 100, 20);
	public static final Move peck = new DefaultMove("Peck", FLYING, PHYSICAL, 35, 100, 35);
	public static final Move petalDance = new DefaultMove("Petal Dance", GRASS, SPECIAL, 120, 100, 10);
	public static final Move pinMissile = new DefaultMove("Pin Missile", BUG, PHYSICAL, 25, 95, 20);
	public static final Move poisonGas = new DefaultMove("Poison Gas", POISON, STATUS, 0, 90, 40);
	public static final Move poisonPowder = new DefaultMove("Poison Powder", POISON, STATUS, 0, 75, 35);
	public static final Move poisonSting = new DefaultMove("Poison Sting", POISON, PHYSICAL, 15, 100, 35);
	public static final Move pound = new DefaultMove("Pound", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move psybeam = new DefaultMove("Psybeam", PSYCHIC, SPECIAL, 65, 100, 20);
	public static final Move psychic = new DefaultMove("Psychic", PSYCHIC, SPECIAL, 90, 100, 10);
	public static final Move psywave = new DefaultMove("Psywave", PSYCHIC, SPECIAL, 0, 80, 15);
	public static final Move quickAttack = new DefaultMove("Quick Attack", NORMAL, PHYSICAL, 40, 100, 30);
	public static final Move rage = new DefaultMove("Rage", NORMAL, PHYSICAL, 20, 100, 20);
	public static final Move razorLeaf = new DefaultMove("Razor Leaf", GRASS, PHYSICAL, 55, 95, 10);
	public static final Move razorWind = new DefaultMove("Razor Wind", NORMAL, SPECIAL, 80, 100, 10);
	public static final Move recover = new DefaultMove("Recover", NORMAL, STATUS, 0, 0, 10);
	public static final Move reflect = new DefaultMove("Reflect", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move rest = new DefaultMove("Rest", PSYCHIC, STATUS, 0, 0, 10);
	public static final Move roar = new DefaultMove("Roar", NORMAL, STATUS, 0, 0, 20);
	public static final Move rockSlide = new DefaultMove("Rock Slide", ROCK, PHYSICAL, 75, 90, 10);
	public static final Move rockThrow = new DefaultMove("Rock Throw", ROCK, PHYSICAL, 50, 90, 15);
	public static final Move rollingKick = new DefaultMove("Rolling Kick", FIGHTING, PHYSICAL, 60, 85, 15);
	public static final Move sandAttack = new DefaultMove("Sand Attack", GROUND, STATUS, 0, 100, 15);
	public static final Move scratch = new DefaultMove("Scratch", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move screech = new DefaultMove("Screech", NORMAL, STATUS, 0, 85, 40);
	public static final Move seismicToss = new DefaultMove("Seismic Toss", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move selfDestruct = new DefaultMove("Self Destruct", NORMAL, PHYSICAL, 200, 100, 5);
	public static final Move sharpen = new DefaultMove("Sharpen", NORMAL, STATUS, 0, 0, 30);
	public static final Move sing = new DefaultMove("Sing", NORMAL, STATUS, 0, 55, 15);
	public static final Move skullBash = new DefaultMove("Skull Bash", NORMAL, PHYSICAL, 130, 100, 10);
	public static final Move skyAttack = new DefaultMove("Sky Attack", FLYING, PHYSICAL, 140, 90, 5);
	public static final Move slam = new DefaultMove("Slam", NORMAL, PHYSICAL, 80, 75, 20);
	public static final Move slash = new DefaultMove("Slash", NORMAL, PHYSICAL, 75, 100, 20);
	public static final Move sleepPowder = new DefaultMove("Sleep Powder", GRASS, STATUS, 0, 75, 15);
	public static final Move sludge = new DefaultMove("Sludge", POISON, SPECIAL, 65, 100, 20);
	public static final Move smog = new DefaultMove("Smog", POISON, SPECIAL, 30, 70, 20);
	public static final Move smokescreen = new DefaultMove("Smokescreen", NORMAL, STATUS, 0, 100, 20);
	public static final Move softBoiled = new DefaultMove("Soft Boiled", NORMAL, STATUS, 0, 0, 10);
	public static final Move solarBeam = new DefaultMove("Solar Beam", GRASS, SPECIAL, 120, 100, 10);
	public static final Move sonicBoom = new DefaultMove("Sonic Boom", NORMAL, SPECIAL, 0, 90, 20);
	public static final Move spikeCannon = new DefaultMove("Spike Cannon", NORMAL, PHYSICAL, 20, 100, 15);
	public static final Move splash = new DefaultMove("Splash", NORMAL, STATUS, 0, 0, 40);
	public static final Move spore = new DefaultMove("Spore", GRASS, STATUS, 0, 100, 15);
	public static final Move stomp = new DefaultMove("Stomp", NORMAL, PHYSICAL, 65, 100, 20);
	public static final Move strength = new DefaultMove("Strength", NORMAL, PHYSICAL, 80, 100, 15);
	public static final Move stringShot = new DefaultMove("String Shot", BUG, STATUS, 0, 95, 40);
	public static final Move struggle = new DefaultMove("Struggle", NORMAL, PHYSICAL, 50, 100, 0);
	public static final Move stunSpore = new DefaultMove("Stun Spore", GRASS, STATUS, 0, 75, 30);
	public static final Move submission = new DefaultMove("Submission", FIGHTING, PHYSICAL, 80, 80, 20);
	public static final Move substitute = new DefaultMove("Substitute", NORMAL, STATUS, 0, 0, 10);
	public static final Move superFang = new DefaultMove("Super Fang", NORMAL, PHYSICAL, 0, 90, 10);
	public static final Move supersonic = new DefaultMove("Supersonic", NORMAL, STATUS, 0, 55, 20);
	public static final Move surf = new DefaultMove("Surf", WATER, SPECIAL, 90, 100, 15);
	public static final Move swift = new DefaultMove("Swift", NORMAL, SPECIAL, 60, -1, 20);
	public static final Move swordsDance = new DefaultMove("Swords Dance", NORMAL, STATUS, 0, 0, 20);
	public static final Move tackle = new DefaultMove("Tackle", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move tailWhip = new DefaultMove("Tail Whip", NORMAL, STATUS, 0, 100, 30);
	public static final Move takeDown = new DefaultMove("Take Down", NORMAL, PHYSICAL, 90, 85, 20);
	public static final Move teleport = new DefaultMove("Teleport", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move thrash = new DefaultMove("Thrash", NORMAL, PHYSICAL, 120, 100, 10);
	public static final Move thunder = new DefaultMove("Thunder", ELECTRIC, SPECIAL, 110, 70, 10);
	public static final Move thunderPunch = new DefaultMove("Thunder Punch", ELECTRIC, PHYSICAL, 75, 100, 15);
	public static final Move thunderShock = new DefaultMove("Thunder Shock", ELECTRIC, SPECIAL, 40, 100, 30);
	public static final Move thunderWave = new DefaultMove("Thunder Wave", ELECTRIC, STATUS, 0, 90, 20);
	public static final Move thunderbolt = new DefaultMove("Thunderbolt", ELECTRIC, SPECIAL, 90, 100, 15);
	public static final Move toxic = new DefaultMove("Toxic", POISON, STATUS, 0, 90, 10);
	public static final Move transform = new DefaultMove("Transform", NORMAL, STATUS, 0, 0, 10);
	public static final Move triAttack = new DefaultMove("Tri Attack", NORMAL, SPECIAL, 80, 100, 10);
	public static final Move twineedle = new DefaultMove("Twineedle", BUG, PHYSICAL, 25, 100, 20);
	public static final Move viceGrip = new DefaultMove("Vice Grip", NORMAL, PHYSICAL, 55, 100, 30);
	public static final Move vineWhip = new VineWhip("Vine Whip", GRASS, PHYSICAL, 45, 100, 25);
	public static final Move waterGun = new DefaultMove("Water Gun", WATER, SPECIAL, 40, 100, 25);
	public static final Move waterfall = new DefaultMove("Waterfall", WATER, PHYSICAL, 80, 100, 15);
	public static final Move whirlwind = new DefaultMove("Whirlwind", NORMAL, STATUS, 0, 0, 20);
	public static final Move wingAttack = new DefaultMove("Wing Attack", FLYING, PHYSICAL, 60, 100, 35);
	public static final Move withdraw = new DefaultMove("Withdraw", WATER, STATUS, 0, 0, 40);
	public static final Move wrap = new DefaultMove("Wrap", NORMAL, PHYSICAL, 15, 90, 20);

	@Override
	public void preInit() {}

	@Override
	public void init() {
		for (Move m : Move.moves) Debug.debug(m);
	}

	@Override
	public void postInit() {}
}
