package ninja.cooperstuff.pokemon.init;

import ninja.cooperstuff.debug.Debug;
import ninja.cooperstuff.pokemon.move.Move;

import static ninja.cooperstuff.pokemon.init.Types.*;
import static ninja.cooperstuff.pokemon.move.Move.AttackType.*;

public class Moves implements Init.Initializer {
	public static final Move absorb = new Move("Absorb", GRASS, SPECIAL, 20, 100, 25);
	public static final Move acid = new Move("Acid", POISON, SPECIAL, 40, 100, 30);
	public static final Move acidArmor = new Move("Acid Armor", POISON, STATUS, 0, 0, 20);
	public static final Move agility = new Move("Agility", PSYCHIC, STATUS, 0, 0, 30);
	public static final Move amnesia = new Move("Amnesia", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move auroraBeam = new Move("Aurora Beam", ICE, SPECIAL, 65, 100, 20);
	public static final Move barrage = new Move("Barrage", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move barrier = new Move("Barrier", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move bide = new Move("Bide", NORMAL, PHYSICAL, 0, 0, 10);
	public static final Move bind = new Move("Bind", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move bite = new Move("Bite", DARK, PHYSICAL, 60, 100, 25);
	public static final Move blizzard = new Move("Blizzard", ICE, SPECIAL, 110, 70, 5);
	public static final Move bodySlam = new Move("Body Slam", NORMAL, PHYSICAL, 85, 100, 15);
	public static final Move boneClub = new Move("Bone Club", GROUND, PHYSICAL, 65, 85, 20);
	public static final Move bonemerang = new Move("Bonemerang", GROUND, PHYSICAL, 50, 90, 10);
	public static final Move bubble = new Move("Bubble", WATER, SPECIAL, 40, 100, 30);
	public static final Move bubbleBeam = new Move("Bubble Beam", WATER, SPECIAL, 65, 100, 20);
	public static final Move clamp = new Move("Clamp", WATER, PHYSICAL, 35, 85, 10);
	public static final Move cometPunch = new Move("Comet Punch", NORMAL, PHYSICAL, 18, 85, 15);
	public static final Move confuseRay = new Move("Confuse Ray", GHOST, STATUS, 0, 100, 10);
	public static final Move confusion = new Move("Confusion", PSYCHIC, SPECIAL, 50, 100, 25);
	public static final Move constrict = new Move("Constrict", NORMAL, PHYSICAL, 10, 100, 35);
	public static final Move conversion = new Move("Conversion", NORMAL, STATUS, 0, 0, 30);
	public static final Move counter = new Move("Counter", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move crabhammer = new Move("Crabhammer", WATER, PHYSICAL, 100, 90, 10);
	public static final Move cut = new Move("Cut", NORMAL, PHYSICAL, 50, 95, 30);
	public static final Move defenceCurl = new Move("Defence Curl", NORMAL, STATUS, 0, 0, 40);
	public static final Move dig = new Move("Dig", GROUND, PHYSICAL, 80, 100, 10);
	public static final Move disable = new Move("Disable", NORMAL, STATUS, 0, 100, 20);
	public static final Move dizzyPunch = new Move("Dizzy Punch", NORMAL, PHYSICAL, 70, 100, 10);
	public static final Move doubleKick = new Move("Double Kick", FIGHTING, PHYSICAL, 30, 100, 30);
	public static final Move doubleSlap = new Move("Double Slap", NORMAL, PHYSICAL, 15, 85, 10);
	public static final Move doubleTeam = new Move("Double Team", NORMAL, STATUS, 0, 0, 15);
	public static final Move doubleEdge = new Move("Double Edge", NORMAL, PHYSICAL, 120, 100, 15);
	public static final Move dragonRage = new Move("Dragon Rage", DRAGON, SPECIAL, 0, 100, 10);
	public static final Move dreamEater = new Move("Dream Eater", PSYCHIC, SPECIAL, 100, 100, 15);
	public static final Move drillPeck = new Move("Drill Peck", FLYING, PHYSICAL, 80, 100, 20);
	public static final Move earthquake = new Move("Earthquake", GROUND, PHYSICAL, 100, 100, 10);
	public static final Move eggBomb = new Move("Egg Bomb", NORMAL, PHYSICAL, 100, 75, 10);
	public static final Move ember = new Move("Ember", FIRE, SPECIAL, 40, 100, 25);
	public static final Move explosion = new Move("Explosion", NORMAL, PHYSICAL, 250, 100, 5);
	public static final Move fireBlast = new Move("Fire Blast", FIRE, SPECIAL, 110, 85, 5);
	public static final Move firePunch = new Move("Fire Punch", FIRE, PHYSICAL, 75, 100, 15);
	public static final Move fireSpin = new Move("Fire Spin", FIRE, SPECIAL, 35, 85, 15);
	public static final Move fissure = new Move("Fissure", GROUND, PHYSICAL, 0, 0, 5);
	public static final Move flamethrower = new Move("Flamethrower", FIRE, SPECIAL, 90, 100, 15);
	public static final Move flash = new Move("Flash", NORMAL, STATUS, 0, 100, 20);
	public static final Move fly = new Move("Fly", FLYING, PHYSICAL, 90, 95, 15);
	public static final Move focusEnergy = new Move("Focus Energy", NORMAL, STATUS, 0, 0, 30);
	public static final Move furyAttack = new Move("Fury Attack", NORMAL, PHYSICAL, 15, 85, 20);
	public static final Move furySwipes = new Move("Fury Swipes", NORMAL, PHYSICAL, 18, 80, 15);
	public static final Move glare = new Move("Glare", NORMAL, STATUS, 0, 100, 30);
	public static final Move growl = new Move("Growl", NORMAL, STATUS, 0, 100, 40);
	public static final Move growth = new Move("Growth", NORMAL, STATUS, 0, 0, 40);
	public static final Move guillotine = new Move("Guillotine", NORMAL, PHYSICAL, 0, 0, 5);
	public static final Move gust = new Move("Gust", FLYING, SPECIAL, 40, 100, 35);
	public static final Move harden = new Move("Harden", NORMAL, STATUS, 0, 0, 30);
	public static final Move haze = new Move("Haze", ICE, STATUS, 0, 0, 30);
	public static final Move headbutt = new Move("Headbutt", NORMAL, PHYSICAL, 70, 100, 15);
	public static final Move highJumpKick = new Move("High Jump Kick", FIGHTING, PHYSICAL, 130, 90, 10);
	public static final Move hornAttack = new Move("Horn Attack", NORMAL, PHYSICAL, 65, 100, 25);
	public static final Move hornDrill = new Move("Horn Drill", NORMAL, PHYSICAL, 0, 0, 5);
	public static final Move hydroPump = new Move("Hydro Pump", WATER, SPECIAL, 110, 80, 5);
	public static final Move hyperBeam = new Move("Hyper Beam", NORMAL, SPECIAL, 150, 90, 5);
	public static final Move hyperFang = new Move("Hyper Fang", NORMAL, PHYSICAL, 80, 90, 15);
	public static final Move hypnosis = new Move("Hypnosis", PSYCHIC, STATUS, 0, 60, 20);
	public static final Move iceBeam = new Move("Ice Beam", ICE, SPECIAL, 90, 100, 10);
	public static final Move icePunch = new Move("Ice Punch", ICE, PHYSICAL, 75, 100, 15);
	public static final Move jumpKick = new Move("Jump Kick", FIGHTING, PHYSICAL, 100, 95, 10);
	public static final Move karateChop = new Move("Karate Chop", FIGHTING, PHYSICAL, 50, 100, 25);
	public static final Move kinesis = new Move("Kinesis", PSYCHIC, STATUS, 0, 80, 15);
	public static final Move leechLife = new Move("Leech Life", BUG, PHYSICAL, 80, 100, 10);
	public static final Move leechSeed = new Move("Leech Seed", GRASS, STATUS, 0, 90, 10);
	public static final Move leer = new Move("Leer", NORMAL, STATUS, 0, 100, 30);
	public static final Move lick = new Move("Lick", GHOST, PHYSICAL, 30, 100, 30);
	public static final Move lightScreen = new Move("Light Screen", PSYCHIC, STATUS, 0, 0, 30);
	public static final Move lovelyKiss = new Move("Lovely Kiss", NORMAL, STATUS, 0, 75, 10);
	public static final Move lowKick = new Move("Low Kick", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move meditate = new Move("Meditate", PSYCHIC, STATUS, 0, 0, 40);
	public static final Move megaDrain = new Move("Mega Drain", GRASS, SPECIAL, 40, 100, 15);
	public static final Move megaKick = new Move("Mega Kick", NORMAL, PHYSICAL, 120, 75, 5);
	public static final Move megaPunch = new Move("Mega Punch", NORMAL, PHYSICAL, 80, 85, 20);
	public static final Move metronome = new Move("Metronome", NORMAL, STATUS, 0, 0, 10);
	public static final Move mimic = new Move("Mimic", NORMAL, STATUS, 0, 0, 10);
	public static final Move minimize = new Move("Minimize", NORMAL, STATUS, 0, 0, 10);
	public static final Move mirrorMove = new Move("Mirror Move", FLYING, STATUS, 0, 0, 20);
	public static final Move mist = new Move("Mist", ICE, STATUS, 0, 0, 30);
	public static final Move nightShade = new Move("Night Shade", GHOST, SPECIAL, 0, 100, 15);
	public static final Move payDay = new Move("Pay Day", NORMAL, PHYSICAL, 40, 100, 20);
	public static final Move peck = new Move("Peck", FLYING, PHYSICAL, 35, 100, 35);
	public static final Move petalDance = new Move("Petal Dance", GRASS, SPECIAL, 120, 100, 10);
	public static final Move pinMissile = new Move("Pin Missile", BUG, PHYSICAL, 25, 95, 20);
	public static final Move poisonGas = new Move("Poison Gas", POISON, STATUS, 0, 90, 40);
	public static final Move poisonPowder = new Move("Poison Powder", POISON, STATUS, 0, 75, 35);
	public static final Move poisonSting = new Move("Poison Sting", POISON, PHYSICAL, 15, 100, 35);
	public static final Move pound = new Move("Pound", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move psybeam = new Move("Psybeam", PSYCHIC, SPECIAL, 65, 100, 20);
	public static final Move psychic = new Move("Psychic", PSYCHIC, SPECIAL, 90, 100, 10);
	public static final Move psywave = new Move("Psywave", PSYCHIC, SPECIAL, 0, 80, 15);
	public static final Move quickAttack = new Move("Quick Attack", NORMAL, PHYSICAL, 40, 100, 30);
	public static final Move rage = new Move("Rage", NORMAL, PHYSICAL, 20, 100, 20);
	public static final Move razorLeaf = new Move("Razor Leaf", GRASS, PHYSICAL, 55, 95, 10);
	public static final Move razorWind = new Move("Razor Wind", NORMAL, SPECIAL, 80, 100, 10);
	public static final Move recover = new Move("Recover", NORMAL, STATUS, 0, 0, 10);
	public static final Move reflect = new Move("Reflect", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move rest = new Move("Rest", PSYCHIC, STATUS, 0, 0, 10);
	public static final Move roar = new Move("Roar", NORMAL, STATUS, 0, 0, 20);
	public static final Move rockSlide = new Move("Rock Slide", ROCK, PHYSICAL, 75, 90, 10);
	public static final Move rockThrow = new Move("Rock Throw", ROCK, PHYSICAL, 50, 90, 15);
	public static final Move rollingKick = new Move("Rolling Kick", FIGHTING, PHYSICAL, 60, 85, 15);
	public static final Move sandAttack = new Move("Sand Attack", GROUND, STATUS, 0, 100, 15);
	public static final Move scratch = new Move("Scratch", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move screech = new Move("Screech", NORMAL, STATUS, 0, 85, 40);
	public static final Move seismicToss = new Move("Seismic Toss", FIGHTING, PHYSICAL, 0, 100, 20);
	public static final Move selfDestruct = new Move("Self Destruct", NORMAL, PHYSICAL, 200, 100, 5);
	public static final Move sharpen = new Move("Sharpen", NORMAL, STATUS, 0, 0, 30);
	public static final Move sing = new Move("Sing", NORMAL, STATUS, 0, 55, 15);
	public static final Move skullBash = new Move("Skull Bash", NORMAL, PHYSICAL, 130, 100, 10);
	public static final Move skyAttack = new Move("Sky Attack", FLYING, PHYSICAL, 140, 90, 5);
	public static final Move slam = new Move("Slam", NORMAL, PHYSICAL, 80, 75, 20);
	public static final Move slash = new Move("Slash", NORMAL, PHYSICAL, 75, 100, 20);
	public static final Move sleepPowder = new Move("Sleep Powder", GRASS, STATUS, 0, 75, 15);
	public static final Move sludge = new Move("Sludge", POISON, SPECIAL, 65, 100, 20);
	public static final Move smog = new Move("Smog", POISON, SPECIAL, 30, 70, 20);
	public static final Move smokescreen = new Move("Smokescreen", NORMAL, STATUS, 0, 100, 20);
	public static final Move softBoiled = new Move("Soft Boiled", NORMAL, STATUS, 0, 0, 10);
	public static final Move solarBeam = new Move("Solar Beam", GRASS, SPECIAL, 120, 100, 10);
	public static final Move sonicBoom = new Move("Sonic Boom", NORMAL, SPECIAL, 0, 90, 20);
	public static final Move spikeCannon = new Move("Spike Cannon", NORMAL, PHYSICAL, 20, 100, 15);
	public static final Move splash = new Move("Splash", NORMAL, STATUS, 0, 0, 40);
	public static final Move spore = new Move("Spore", GRASS, STATUS, 0, 100, 15);
	public static final Move stomp = new Move("Stomp", NORMAL, PHYSICAL, 65, 100, 20);
	public static final Move strength = new Move("Strength", NORMAL, PHYSICAL, 80, 100, 15);
	public static final Move stringShot = new Move("String Shot", BUG, STATUS, 0, 95, 40);
	public static final Move struggle = new Move("Struggle", NORMAL, PHYSICAL, 50, 100, 0);
	public static final Move stunSpore = new Move("Stun Spore", GRASS, STATUS, 0, 75, 30);
	public static final Move submission = new Move("Submission", FIGHTING, PHYSICAL, 80, 80, 20);
	public static final Move substitute = new Move("Substitute", NORMAL, STATUS, 0, 0, 10);
	public static final Move superFang = new Move("Super Fang", NORMAL, PHYSICAL, 0, 90, 10);
	public static final Move supersonic = new Move("Supersonic", NORMAL, STATUS, 0, 55, 20);
	public static final Move surf = new Move("Surf", WATER, SPECIAL, 90, 100, 15);
	public static final Move swift = new Move("Swift", NORMAL, SPECIAL, 60, -1, 20);
	public static final Move swordsDance = new Move("Swords Dance", NORMAL, STATUS, 0, 0, 20);
	public static final Move tackle = new Move("Tackle", NORMAL, PHYSICAL, 40, 100, 35);
	public static final Move tailWhip = new Move("Tail Whip", NORMAL, STATUS, 0, 100, 30);
	public static final Move takeDown = new Move("Take Down", NORMAL, PHYSICAL, 90, 85, 20);
	public static final Move teleport = new Move("Teleport", PSYCHIC, STATUS, 0, 0, 20);
	public static final Move thrash = new Move("Thrash", NORMAL, PHYSICAL, 120, 100, 10);
	public static final Move thunder = new Move("Thunder", ELECTRIC, SPECIAL, 110, 70, 10);
	public static final Move thudnerPunch = new Move("Thudner Punch", ELECTRIC, PHYSICAL, 75, 100, 15);
	public static final Move thunderShock = new Move("Thunder Shock", ELECTRIC, SPECIAL, 40, 100, 30);
	public static final Move thunderWave = new Move("Thunder Wave", ELECTRIC, STATUS, 0, 90, 20);
	public static final Move thunderbolt = new Move("Thunderbolt", ELECTRIC, SPECIAL, 90, 100, 15);
	public static final Move toxic = new Move("Toxic", POISON, STATUS, 0, 90, 10);
	public static final Move transform = new Move("Transform", NORMAL, STATUS, 0, 0, 10);
	public static final Move triAttack = new Move("Tri Attack", NORMAL, SPECIAL, 80, 100, 10);
	public static final Move twineedle = new Move("Twineedle", BUG, PHYSICAL, 25, 100, 20);
	public static final Move viceGrip = new Move("Vice Grip", NORMAL, PHYSICAL, 55, 100, 30);
	public static final Move vineWhip = new Move("Vine Whip", GRASS, PHYSICAL, 45, 100, 25);
	public static final Move waterGun = new Move("Water Gun", WATER, SPECIAL, 40, 100, 25);
	public static final Move waterfall = new Move("Waterfall", WATER, PHYSICAL, 80, 100, 15);
	public static final Move whirlwind = new Move("Whirlwind", NORMAL, STATUS, 0, 0, 20);
	public static final Move wingAttack = new Move("Wing Attack", FLYING, PHYSICAL, 60, 100, 35);
	public static final Move withdraw = new Move("Withdraw", WATER, STATUS, 0, 0, 40);
	public static final Move wrap = new Move("Wrap", NORMAL, PHYSICAL, 15, 90, 20);

	@Override
	public void preInit() {}

	@Override
	public void init() {
		for (Move m : Move.moves) Debug.debug(m);
	}

	@Override
	public void postInit() {}
}
